FROM node:12-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

EXPOSE 8080

COPY ./package.json *yarn* ./

RUN yarn upgrade

COPY . /app

RUN yarn build

FROM nginx:1.17

COPY --from=builder /app/dist/ /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
