version: "3"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/nginx.dev.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=$PROJECT_SLUG.local
      - VIRTUAL_PORT=8080
    links:
      - client
      - server
    networks:
      - proxynet
      - default
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    networks:
      - default
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/var/www
    links:
      - db:db
    environment:
      - DB_NAME=${PROJECT_SLUG}
      - DB_USER=${PROJECT_SLUG}
      - DB_PASSWORD=${PROJECT_SLUG}_db_password
      - DB_HOST=db
      - DB_PORT=3306
    networks:
      - default
  db:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "${PROJECT_SLUG}", "-p${PROJECT_SLUG}_db_password"]
      timeout: 20s
      retries: 10
    ports:
      - ${DB_PROBE_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=${PROJECT_SLUG}
      - MYSQL_USER=${PROJECT_SLUG}
      - MYSQL_PASSWORD=${PROJECT_SLUG}_db_password
    networks:
      - default

volumes:
  database:
    driver: local


networks:
  proxynet:
    external:
      name: proxy_network
  default:
