version: '3.5'

services:
  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    image: ${PROJECT_SLUG}-prod-mobile:latest
    environment:
      - VIRTUAL_HOST=${PROD_MOBILE_URL}
      - VIRTUAL_PORT=80
    networks:
      - proxynet
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    image: ${PROJECT_SLUG}-prod-web
    environment:
      - VIRTUAL_HOST=${PROD_APP_URL}
      - VIRTUAL_PORT=8080
    volumes:
      - avatars:/var/www/avatars
    links:
      - client
      - server
    networks:
      - proxynet
      - default
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: ${PROJECT_SLUG}-prod-client
    networks:
      - default
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: ${PROJECT_SLUG}-prod-server
    links:
      - db:db
    environment:
      - DB_NAME=${PROJECT_SLUG}
      - DB_USER=${PROJECT_SLUG}
      - DB_PASSWORD=${PROJECT_SLUG}_db_password
      - DB_HOST=db
      - DB_PORT=3306
    networks:
      - default
  db:
    image: mysql:5.6
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "${PROJECT_SLUG}", "-p${PROJECT_SLUG}_db_password"]
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=${PROJECT_SLUG}
      - MYSQL_USER=${PROJECT_SLUG}
      - MYSQL_PASSWORD=${PROJECT_SLUG}_db_password

volumes:
  mysql-data:
    driver: local

networks:
  proxynet:
    external:
      name: proxy_network
